### PR TITLE
Adds wagecan plugin files

### PR DESCRIPTION
**Pull request by johnny77221**

### CODE REVIEW

**Comment by paullinator** [comment]
Cool. the plugin looks great. But I have some comments:

1. Can we change the wording of "Use Airbitz's referral code to get 20% off" to "Click here to get 20% off". This can be a direct link to your website using our referral code. No need to show the actual link and have the user copy/paste. Just make it an <a href> in your HTML

2. It seems like the Exchange Rate and Estimated Top Up Value are just "N/A". Is this expected?

**Comment by paullinator** [comment]
One other small suggestion. When the user enters the last 8 digits of their card, you should automatically focus on the 2nd text field after they enter the 4 digits in the first text field. Makes for a much smoother UX

**Comment by paullinator** [comment]
Also, please send a valid 8 digit card num that I can use to see the entire flow of the plugin.

Thanks

**Comment by johnny77221** [comment]
Hi, Paul

1. We've tried document.execCommand('copy'); but it doesn't seem to be working in an iOS WebView (the stackoverflow article also proved this), if main app supports extra url scheme to open a link in safari or copy, then we will use the designed url scheme
2. N/A will be good after you entered a valid card number (the currency will change), for example, a card 7061 7722 will be a USD card
3. The auto focus in javascript also failed when we tried to, if you have suggested script, please kindly teach me
4. We think user should browse our site on external browser for security reason, the registration is recommended on the browser(safari/chrome), instead inside a webview. either on iOS or Android

Thank you very much for your suggestions, all recommends are very user-friendly. Would you mind publishing an existing version and do the improvements in the future versions?

**Comment by paullinator** [comment]
You can open a link in the external browser by using the `launchExternal()` API call. See this for examples

https://github.com/Airbitz/airbitz-plugins/search?utf8=%E2%9C%93&q=launchExternal&type=

2nd issues isn't a big deal, so if you can get the external link to work, I'll approve the PR and get this plugin rolling! :)

**Comment by johnny77221** [comment]
Hi, Paul

Just have a commit on according to your suggestions, please review again

thank you

**Pull request merged**
